import type { Metadata } from "next";
import { Montserrat, Roboto } from "next/font/google";
import "./globals.css";
import Navbar from './components/Navbar'
import localFont from 'next/font/local'


const neueMontreal = localFont({
  variable: "--font-neueMontreal",
  src: [
    {
      path: './fonts/NeueMontreal-Regular.otf',
      weight: '400',
      style: 'normal',
    },
    {
      path: './fonts/NeueMontreal-Bold.otf',
      weight: '700',
      style: 'normal',
    },
    {
      path: './fonts/NeueMontreal-Medium.otf',
      weight: '500',
      style: 'normal',
    },
  ],
})
const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
  display: 'swap',
});
const roboto = Roboto({
  weight: '700',
  variable: "--font-roboto",
  subsets: ["latin"],
  display: 'swap',
});

// const neueMontreal = Neue_Montreal({
//   variable: "--font-neue-montreal",
//   subsets: ["latin"],
//   display: 'swap',
// });

export const metadata: Metadata = {
  title: "NipeX",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.variable} ${roboto.variable} ${neueMontreal.variable} antialiased`}
      >
        <Navbar/>
        {children}
      </body>
    </html>
  );
}
